# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: DEPLOY

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    # - run: npm test

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        # ftp server
        server: ${{secrets.FTP_SERVER}}
        # ftp username
        username: ${{secrets.FTP_USER}}
        # ftp password
        password: ${{secrets.FTP_PASS}}
        # Folder to upload from, must end with trailing slash /
        local-dir: build/
        # Path to upload to on the server. Must end with trailing slash /
        server-dir: public_html/
        # Prints which modifications will be made with current config options, but doesnt actually make any changes
        dry-run: # optional
        # Deletes ALL contents of server-dir, even items in excluded with exclude argument
        dangerous-clean-slate: # optional
        # How verbose should the information be - warn, info, debug
        log-level: standard